export const DO_LOGIN = "DO_LOGIN";
export const DO_LOGIN_SUCCESS = "DO_LOGIN_SUCCESS";
export const DO_LOGOUT = "DO_LOGOUT";
export const DO_LOGOUT_SUCCESS = "DO_LOGOUT_SUCCESS";
export const DO_CHANGE_LOCALE = "DO_CHANGE_LOCALE";
export const DO_CHANGE_LOCALE_SUCCESS = "DO_CHANGE_LOCALE_SUCCESS";
export const SET_ADDRESS_FLOW = "SET_ADDRESS_FLOW";
export const SET_ADDRESS_FLOW_SUCCESS = "SET_ADDRESS_FLOW_SUCCESS";
export const SHOW_MOON_PAY = "SHOW_MOON_PAY"
export const SHOW_PAYMENT_MODAL = "SHOW_PAYMENT_MODAL"
export const SAVE_USER_WALLETS = "SAVE_USER_WALLETS"


